spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
