spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gifts
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
